# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy0boQUG1RAJlZNZe7I8SEYflGsWTWnC
"""

def caesar_encrypt(text, shift):
    encrypted = ""
    for char in text:
        if char.isalpha():
            shift_base = 65 if char.isupper() else 97
            encrypted += chr((ord(char) - shift_base + shift) % 26 + shift_base)
        else:
            encrypted += char
    return encrypted

def caesar_decrypt(text, shift):
    return caesar_encrypt(text, -shift)

def main():
    print("Caesar Cipher Program")
    while True:
        choice = input("\nChoose an option (encrypt/decrypt/exit): ").strip().lower()

        if choice == 'encrypt':
            message = input("Enter the message to encrypt: ")
            try:
                shift = int(input("Enter shift value (integer): "))
                encrypted_msg = caesar_encrypt(message, shift)
                print(f"Encrypted message: {encrypted_msg}")
            except ValueError:
                print("Shift value must be an integer.")

        elif choice == 'decrypt':
            message = input("Enter the message to decrypt: ")
            try:
                shift = int(input("Enter shift value (integer): "))
                decrypted_msg = caesar_decrypt(message, shift)
                print(f"Decrypted message: {decrypted_msg}")
            except ValueError:
                print("Shift value must be an integer.")

        elif choice == 'exit':
            print("Exiting the program.")
            break
        else:
            print("Invalid option. Please choose encrypt, decrypt, or exit.")

if __name__ == "__main__":
    main()