# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy0boQUG1RAJlZNZe7I8SEYflGsWTWnC
"""

from scapy.all import sniff, IP, TCP, UDP, Raw
from datetime import datetime

def packet_callback(packet):
    print("\n--- Packet Captured ---")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    if IP in packet:
        ip_layer = packet[IP]
        print(f"From: {ip_layer.src} --> To: {ip_layer.dst}")
        print(f"Protocol: {ip_layer.proto}")

        if TCP in packet:
            print("Protocol: TCP")
            print(f"Source Port: {packet[TCP].sport} | Destination Port: {packet[TCP].dport}")
        elif UDP in packet:
            print("Protocol: UDP")
            print(f"Source Port: {packet[UDP].sport} | Destination Port: {packet[UDP].dport}")

        if Raw in packet:
            payload = packet[Raw].load
            try:
                print("Payload:", payload.decode(errors='ignore'))
            except:
                print("Payload: [Binary data]")

def main():
    print("🛰️  Starting Packet Sniffer...")
    print("Press Ctrl+C to stop.\n")
    sniff(prn=packet_callback, store=False)

if __name__ == "__main__":
    main()