# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy0boQUG1RAJlZNZe7I8SEYflGsWTWnC
"""

import re

def check_password_strength(password):
    strength_score = 0
    feedback = []

    # Check length
    if len(password) >= 8:
        strength_score += 1
    else:
        feedback.append("Password should be at least 8 characters long.")

    # Check for uppercase
    if re.search(r"[A-Z]", password):
        strength_score += 1
    else:
        feedback.append("Add at least one uppercase letter (A-Z).")

    # Check for lowercase
    if re.search(r"[a-z]", password):
        strength_score += 1
    else:
        feedback.append("Add at least one lowercase letter (a-z).")

    # Check for digits
    if re.search(r"\d", password):
        strength_score += 1
    else:
        feedback.append("Include at least one digit (0-9).")

    # Check for special characters
    if re.search(r"[!@#$%^&*()\-_=+<>?/\\[\]{}|~`]", password):
        strength_score += 1
    else:
        feedback.append("Include at least one special character (!@#$%^&* etc.).")

    # Final assessment
    if strength_score == 5:
        return "Strong password 💪", []
    elif strength_score >= 3:
        return "Moderate password 🛡️", feedback
    else:
        return "Weak password ❌", feedback

def main():
    print("🔐 Password Strength Checker 🔐")
    password = input("Enter your password to check: ")
    strength, suggestions = check_password_strength(password)

    print("\nResult:", strength)
    if suggestions:
        print("Suggestions:")
        for suggestion in suggestions:
            print(f" - {suggestion}")

if __name__ == "__main__":
    main()